package datuak;

// Generated 25-feb-2013 18:35:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Partida generated by hbm2java
 */
public class Partida implements java.io.Serializable {

	private int partidaKodea;
	private Date data;
	private Integer pertsonaKop;
	private Set totalas = new HashSet(0);

	public Partida() {
	}

	public Partida(int partidaKodea) {
		this.partidaKodea = partidaKodea;
	}

	public Partida(int partidaKodea, Date data, Integer pertsonaKop, Set totalas) {
		this.partidaKodea = partidaKodea;
		this.data = data;
		this.pertsonaKop = pertsonaKop;
		this.totalas = totalas;
	}

	public int getPartidaKodea() {
		return this.partidaKodea;
	}

	public void setPartidaKodea(int partidaKodea) {
		this.partidaKodea = partidaKodea;
	}

	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	public Integer getPertsonaKop() {
		return this.pertsonaKop;
	}

	public void setPertsonaKop(Integer pertsonaKop) {
		this.pertsonaKop = pertsonaKop;
	}

	public Set getTotalas() {
		return this.totalas;
	}

	public void setTotalas(Set totalas) {
		this.totalas = totalas;
	}

}
