package datuak;

// Generated 25-feb-2013 18:35:59 by Hibernate Tools 3.4.0.CR1

/**
 * TotalaId generated by hbm2java
 */
public class TotalaId implements java.io.Serializable {

	private String taldea;
	private int partida;

	public TotalaId() {
	}

	public TotalaId(String taldea, int partida) {
		this.taldea = taldea;
		this.partida = partida;
	}

	public String getTaldea() {
		return this.taldea;
	}

	public void setTaldea(String taldea) {
		this.taldea = taldea;
	}

	public int getPartida() {
		return this.partida;
	}

	public void setPartida(int partida) {
		this.partida = partida;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TotalaId))
			return false;
		TotalaId castOther = (TotalaId) other;

		return ((this.getTaldea() == castOther.getTaldea()) || (this
				.getTaldea() != null && castOther.getTaldea() != null && this
				.getTaldea().equals(castOther.getTaldea())))
				&& (this.getPartida() == castOther.getPartida());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTaldea() == null ? 0 : this.getTaldea().hashCode());
		result = 37 * result + this.getPartida();
		return result;
	}

}
